server:
  port: ${SERVER_PORT:4001}
  servlet:
    context-path: "/api/v1/"


jwt:
  secret: secretkey123

Spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/todo?autoReconnect=true&useSSL=false
    username: root
    password: Pass$1234
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update


  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: Log/Logs.log

main:
  allow-circular-references: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false